name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x
      - run: deno fmt --check
      - run: deno lint
      - run: deno task test
      - run: deno coverage ./coverage --lcov --exclude="test" --exclude="bundles" > coverage.lcov
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests
      - run: deno run -A dnt.ts 0.11.3
      - run: mkdir test/browser/src
      - run: cp npm/esm/*.js test/browser/src/
      - run: cp -rf npm/esm/src test/browser/src/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./test/browser
