name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run deno test
        run: |
          deno fmt --check
          deno task test
          deno task cov > coverage.lcov
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests
      - name: Run deno test for /core
        working-directory: ./core
        run: |
          deno fmt --check
          deno task test
      - name: Run deno test for /x/dhkem-x25519
        working-directory: ./x/dhkem-x25519
        run: |
          deno fmt --check
          deno task test
      - name: Run deno test for /x/dhkem-x448
        working-directory: ./x/dhkem-x448
        run: |
          deno fmt --check
          deno task test
      - name: Run deno test for /x/chacha20poly1305
        working-directory: ./x/chacha20poly1305
        run: |
          deno fmt --check
          deno task test
      - name: Run deno test for /x/dhkem-secp256k1
        working-directory: ./x/dhkem-secp256k1
        run: |
          deno fmt --check
          deno task test
