name: Browser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: |
          npm install -g esbuild
          deno task dnt
          deno task minify > test/runtimes/browsers/pages/src/hpke.js
          mkdir test/runtimes/browsers/pages/core
          cp -rf core/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/core
          mkdir test/runtimes/browsers/pages/dhkem-secp256k1
          cp -rf x/dhkem-secp256k1/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/dhkem-secp256k1
          deno task minify > test/runtimes/browsers/pages/dhkem-secp256k1/src/hpke.js
      - working-directory: ./core
        run: |
          deno task dnt
          deno task minify > ../test/runtimes/browsers/pages/core/src/hpke-core.js
      - working-directory: ./x/dhkem-secp256k1
        run: |
          deno task dnt
          deno task minify > ../../test/runtimes/browsers/pages/dhkem-secp256k1/src/hpke-dhkem-secp256k1.js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./test/runtimes/browsers/pages

  playwright-test:
    needs: pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - working-directory: ./test/runtimes/browsers
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test
      - working-directory: ./core/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
      - working-directory: ./x/dhkem-secp256k1/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
