name: bun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [0.4, 0.5, 0.6, 0.7]

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: |
          npm install -g esbuild
          deno task dnt
          deno task minify > test/runtimes/hpke.js
          deno task minify > x/dhkem-secp256k1/test/runtimes/hpke.js
      - working-directory: ./x/dhkem-secp256k1/
        run: |
          deno task dnt
          deno task minify > test/runtimes/hpke-dhkem-secp256k1.js
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Run test
        working-directory: ./test/runtimes/bun
        run: |
          nohup bun src/index.js &
          sleep 3
          deno test hpke.spec.ts --allow-net
      - name: Run test for dhkem-secp256k1
        working-directory: ./x/dhkem-secp256k1/test/runtimes/bun
        run: |
          nohup bun src/index.js &
          sleep 3
          deno test dhkem-secp256k1.spec.ts --allow-net