name: Browser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - run: |
          npm install -g typescript
          npm install -g typedoc
          npx typedoc --name "hpke-js $(git describe --tags $(git rev-list --tags --max-count=1))" --out test/runtimes/browsers/pages/docs mod.ts
          npm install -g esbuild
          deno task dnt
          deno task minify > test/runtimes/browsers/pages/src/hpke.js
          mkdir test/runtimes/browsers/pages/core
          cp -rf core/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/core
          mkdir test/runtimes/browsers/pages/dhkem-x25519
          cp -rf x/dhkem-x25519/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/dhkem-x25519
          mkdir test/runtimes/browsers/pages/dhkem-x448
          cp -rf x/dhkem-x448/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/dhkem-x448
          mkdir test/runtimes/browsers/pages/chacha20poly1305
          cp -rf x/chacha20poly1305/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/chacha20poly1305
          mkdir test/runtimes/browsers/pages/dhkem-secp256k1
          cp -rf x/dhkem-secp256k1/test/runtimes/browsers/pages/* test/runtimes/browsers/pages/dhkem-secp256k1
      - working-directory: ./core
        run: |
          npx typedoc --name "@hpke/core $(git describe --tags $(git rev-list --tags --max-count=1))" --out ../test/runtimes/browsers/pages/core/docs mod.ts
          deno task dnt
          deno task minify > ../test/runtimes/browsers/pages/core/src/hpke-core.js
          deno task minify > ../test/runtimes/browsers/pages/dhkem-x25519/src/hpke-core.js
          deno task minify > ../test/runtimes/browsers/pages/dhkem-x448/src/hpke-core.js
          deno task minify > ../test/runtimes/browsers/pages/chacha20poly1305/src/hpke-core.js
          deno task minify > ../test/runtimes/browsers/pages/dhkem-secp256k1/src/hpke-core.js
      - working-directory: ./x/dhkem-x25519
        run: |
          npx typedoc --name "@hpke/dhkem-x25519 $(git describe --tags $(git rev-list --tags --max-count=1))" --out ../../test/runtimes/browsers/pages/dhkem-x25519/docs mod.ts
          deno task dnt
          deno task minify > ../../test/runtimes/browsers/pages/dhkem-x25519/src/hpke-dhkem-x25519.js
      - working-directory: ./x/dhkem-x448
        run: |
          npx typedoc --name "@hpke/dhkem-x448 $(git describe --tags $(git rev-list --tags --max-count=1))" --out ../../test/runtimes/browsers/pages/dhkem-x448/docs mod.ts
          deno task dnt
          deno task minify > ../../test/runtimes/browsers/pages/dhkem-x448/src/hpke-dhkem-x448.js
      - working-directory: ./x/chacha20poly1305
        run: |
          npx typedoc --name "@hpke/chacha20poly1305 $(git describe --tags $(git rev-list --tags --max-count=1))" --out ../../test/runtimes/browsers/pages/chacha20poly1305/docs mod.ts
          deno task dnt
          deno task minify > ../../test/runtimes/browsers/pages/chacha20poly1305/src/hpke-chacha20poly1305.js
      - working-directory: ./x/dhkem-secp256k1
        run: |
          npx typedoc --name "@hpke/dhkem-secp256k1 $(git describe --tags $(git rev-list --tags --max-count=1))" --out ../../test/runtimes/browsers/pages/dhkem-secp256k1/docs mod.ts
          deno task dnt
          deno task minify > ../../test/runtimes/browsers/pages/dhkem-secp256k1/src/hpke-dhkem-secp256k1.js
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./test/runtimes/browsers/pages

  playwright-test:
    needs: pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - working-directory: ./test/runtimes/browsers
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright test
      - working-directory: ./core/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
      - working-directory: ./x/dhkem-x25519/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
      - working-directory: ./x/dhkem-x448/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
      - working-directory: ./x/chacha20poly1305/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
      - working-directory: ./x/dhkem-secp256k1/test/runtimes/browsers
        run: npm install && npx playwright install && npx playwright test
