name: Publish

on:
  release:
    types: [created]

jobs:
  publish-to-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run dnt
        run: |
          deno task test
      - name: Run deno publish
        run: npx jsr publish

  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run deno task npm
        run: |
          npm install -g esbuild
          deno task npm
      - name: Publish @hpke/common to npm
        working-directory: ./npm/packages/common
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/core to npm
        working-directory: ./npm/packages/core
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/chacha20poly1305 to npm
        working-directory: ./npm/packages/chacha20poly1305
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/dhkem-x25519 to npm
        working-directory: ./npm/packages/dhkem-x25519
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/dhkem-x448 to npm
        working-directory: ./npm/packages/dhkem-x448
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/hybridkem-x25519-kyber768 to npm
        working-directory: ./npm/packages/hybridkem-x25519-kyber768
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish @hpke/dhkem-secp256k1 to npm
        working-directory: ./npm/packages/dhkem-secp256k1
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish hpke-js to npm
        working-directory: ./npm/packages/hpke-js
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
